<script>
  function loaded() {
    items = window.performance.getEntriesByType("resource")
    {
      item = items[0]
      document.write('<h3>resource summary</h3>')
      document.write('connectEnd: ' + item.connectEnd + '<br>')
      document.write('connectStart: ' + item.connectStart + '<br>')
      document.write('domainLookupEnd: ' + item.domainLookupEnd + '<br>')
      document.write('domainLookupStart: ' + item.domainLookupStart + '<br>')
      document.write('duration: ' + item.duration + '<br>')
      document.write('entryType: ' + item.entryType + '<br>')
      document.write('fetchStart: ' + item.fetchStart + '<br>')
      document.write('initiatorType: ' + item.initiatorType + '<br>')
      document.write('name: ' + item.name + '<br>')
      document.write('redirectEnd: ' + item.redirectEnd + '<br>')
      document.write('redirectStart: ' + item.redirectStart + '<br>')
      document.write('requestStart: ' + item.requestStart + '<br>')
      document.write('responseEnd: ' + item.responseEnd + '<br>')
      document.write('responseStart: ' + item.responseStart + '<br>')
      document.write('secureConnectionStart: ' + item.secureConnectionStart + '<br>')
      document.write('startTime: ' + item.startTime + '<br>')
    }
    document.write('<h3>page summary</h3>')
    document.write('navigationStart: ' + window.performance.timing.navigationStart + '<br>')
    document.write('redirectStart: ' + window.performance.timing.redirectStart + '<br>')
    document.write('redirectEnd: ' + window.performance.timing.redirectEnd + '<br>')
    document.write('fetchStart: ' + window.performance.timing.fetchStart + '<br>')
    document.write('domainLookupStart: ' + window.performance.timing.domainLookupStart + '<br>')
    document.write('domainLookupEnd: ' + window.performance.timing.domainLookupEnd + '<br>')
    document.write('connectStart: ' + window.performance.timing.connectEnd + '<br>')
    document.write('secureConnectionStart: ' + window.performance.timing.secureConnectionStart + '<br>')
    document.write('connectEnd : ' + window.performance.timing.loadEventEnd + '<br>')
    document.write('requestStart: ' + window.performance.timing.requestStart + '<br>')
    document.write('responseStart: ' + window.performance.timing.responseStart + '<br>')
    document.write('unloadEventEnd: ' + window.performance.timing.unloadEventEnd + '<br>')
    document.write('unloadEventStart: ' + window.performance.timing.unloadEventStart + '<br>')
    document.write('responseEnd: ' + window.performance.timing.responseEnd + '<br>')
    document.write('domLoading: ' + window.performance.timing.domLoading + '<br>')
    document.write('domInteractive: ' + window.performance.timing.domInteractive + '<br>')
    document.write('domContentLoadedEventStart: ' + window.performance.timing.domContentLoadedEventStart + '<br>')
    document.write('domContentLoadedEventEnd: ' + window.performance.timing.domContentLoadedEventEnd + '<br>')
    document.write('domComplete: ' + window.performance.timing.domComplete + '<br>')
    document.write('loadEventEnd: ' + window.performance.timing.loadEventEnd + '<br>')
    document.write('loadEventStart: ' + window.performance.timing.loadEventStart + '<br>')
  }
</script>
